"""Added address info to user model

Revision ID: 1018054ec2fb
Revises: 91361290c45f
Create Date: 2022-04-07 07:13:44.836509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1018054ec2fb'
down_revision = '91361290c45f'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_foreign_key(None, 'seat', 'play', ['play_id'], ['id'])
        op.add_column('user', sa.Column('apartment', sa.String(length=32), nullable=True))
        op.add_column('user', sa.Column('zip_code', sa.String(length=16), nullable=True))
        op.add_column('user', sa.Column('state', sa.String(length=16), nullable=True))
        # ### end Alembic commands ###
    except sa.exc.OperationalError:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'apartment')
    op.drop_constraint(None, 'seat', type_='foreignkey')
    # ### end Alembic commands ###
