"""Added city to models

Revision ID: 1fb5e185ccc4
Revises: 543819a9be4d
Create Date: 2022-04-08 10:27:07.985526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb5e185ccc4'
down_revision = '543819a9be4d'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('user', sa.Column('city', sa.String(length=64), nullable=True))
        # ### end Alembic commands ###
    except sa.exc.OperationalError:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
