"""

Revision ID: 2f0ed5fb5ddc
Revises: 57b8e4e0d4b2
Create Date: 2022-04-12 13:51:54.984071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f0ed5fb5ddc'
down_revision = '57b8e4e0d4b2'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_constraint('seat_ibfk_3', 'seat', type_='foreignkey')
        op.drop_column('seat', 'user_id')
        # ### end Alembic commands ###
    except sa.exc.OperationalError:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('seat_ibfk_3', 'seat', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
