"""Added in reservations

Revision ID: 412c30eda7f6
Revises: 1fb5e185ccc4
Create Date: 2022-04-10 08:11:26.690021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '412c30eda7f6'
down_revision = '1fb5e185ccc4'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_column('play', 'date')
        op.drop_constraint('seat_ibfk_3', 'seat', type_='foreignkey')
        op.drop_constraint('seat_ibfk_2', 'seat', type_='foreignkey')
        op.drop_column('seat', 'user_id')

    except sa.exc.OperationalError:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('seat_ibfk_2', 'seat', 'user', ['user_id'], ['id'])
    op.create_foreign_key('seat_ibfk_3', 'seat', 'play', ['play_id'], ['id'])
    op.add_column('play', sa.Column('date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
