"""Added user/seat relationship

Revision ID: 456d0dd5cc04
Revises: 6ec82ab9c497
Create Date: 2022-04-07 13:11:06.800681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456d0dd5cc04'
down_revision = '6ec82ab9c497'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('seat', sa.Column('user_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'seat', 'user', ['user_id'], ['id'])
        # ### end Alembic commands ###
    except sa.exc.OperationalError:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seat', type_='foreignkey')
    op.drop_column('seat', 'user_id')
    # ### end Alembic commands ###
