"""Added authentication to user

Revision ID: 543819a9be4d
Revises: 6b7118a24168
Create Date: 2022-04-07 18:04:28.701682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543819a9be4d'
down_revision = '6b7118a24168'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('user', sa.Column('authenticated', sa.Boolean(), nullable=True))
        # ### end Alembic commands ###
    except sa.exc.OperationalError:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authenticated')
    # ### end Alembic commands ###
