"""Added availability to the seat

Revision ID: 6b7111ff5d88
Revises: 8924bae07e5c
Create Date: 2022-04-06 14:25:06.195083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7111ff5d88'
down_revision = '8924bae07e5c'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('seat', sa.Column('available', sa.Boolean(), nullable=True))
        # ### end Alembic commands ###
    except sa.exc.OperationalError:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat', 'available')
    # ### end Alembic commands ###
