"""Fixed address typo

Revision ID: 6ec82ab9c497
Revises: 1018054ec2fb
Create Date: 2022-04-07 07:14:11.213215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec82ab9c497'
down_revision = '1018054ec2fb'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('user', sa.Column('address', sa.String(length=256), nullable=True))
        # ### end Alembic commands ###
    except sa.exc.OperationalError:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
