"""Removed the username field from the user model

Revision ID: 8924bae07e5c
Revises:
Create Date: 2022-03-27 14:21:40.914658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8924bae07e5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_column('user', 'username')
        # ### end Alembic commands ###
    except:
        pass



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False))
    # ### end Alembic commands ###
