"""added nullable constraint

Revision ID: 8ff9f55e0cd3
Revises: 2f0ed5fb5ddc
Create Date: 2022-04-15 16:58:45.651417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ff9f55e0cd3'
down_revision = '2f0ed5fb5ddc'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('date', 'date',
                   existing_type=sa.DATE(),
                   nullable=False)
        op.alter_column('time', 'time',
                   existing_type=mysql.TIME(),
                   nullable=False)
        # ### end Alembic commands ###
    except sa.exc.OperationalError:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time', 'time',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('date', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
