"""seat's play -> play_id

Revision ID: 91361290c45f
Revises: efc8626b89e2
Create Date: 2022-04-06 16:41:40.445968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91361290c45f'
down_revision = 'efc8626b89e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('seat', 'play')
        op.create_foreign_key(None, 'seat', 'play', ['play_id'], ['id'])
        # ### end Alembic commands ###
    except sa.exc.OperationalError:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('play', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'seat', type_='foreignkey')
    # ### end Alembic commands ###
