"""Fixed mapping

Revision ID: 9aeb11347107
Revises: 412c30eda7f6
Create Date: 2022-04-10 08:21:11.083972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9aeb11347107'
down_revision = '412c30eda7f6'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column('seat', 'play_id',
                   existing_type=mysql.INTEGER(display_width=11),
                   nullable=True)
        # ### end Alembic commands ###
    except sa.exc.OperationalError:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seat', 'play_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
