"""Added active column to play

Revision ID: bf9d0c81ecde
Revises: 456d0dd5cc04
Create Date: 2022-04-07 14:28:41.505457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9d0c81ecde'
down_revision = '456d0dd5cc04'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('play', sa.Column('active', sa.Boolean(), nullable=True))
        # ### end Alembic commands ###
    except sa.exc.OperationalError:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('play', 'active')
    # ### end Alembic commands ###
