"""Added reservation date to reservation

Revision ID: d249dfa3cbd8
Revises: c83557b4ca84
Create Date: 2022-05-09 16:35:46.419150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd249dfa3cbd8'
down_revision = 'c83557b4ca84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('reserved', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'reserved')
    # ### end Alembic commands ###
