"""Added rows and columns to seats

Revision ID: efc8626b89e2
Revises: 6b7111ff5d88
Create Date: 2022-04-06 15:48:54.527491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc8626b89e2'
down_revision = '6b7111ff5d88'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('seat', sa.Column('row', sa.Integer(), nullable=False))
        op.add_column('seat', sa.Column('column', sa.Integer(), nullable=False))
        # ### end Alembic commands ###
    except sa.exc.OperationalError:
        pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat', 'column')
    op.drop_column('seat', 'row')
    # ### end Alembic commands ###
